services:
    swosh:
        image: "edholm/swosh:${TAG:-latest}"
        restart: always
        environment:
            - SWOSH_MONGODB_URI=mongodb://mongodb/swosh
            - SWOSH_HOSTNAME=${SWOSH_HOSTNAME:-swosh.me}
            - SWOSH_SCHEME=${SWOSH_SCHEME:-https}
            - SWOSH_PROVISION_USERS=${SWOSH_PROVISION_USERS:-true}
        ports:
            - ${APP_PORT:-8080}:8080
            - ${ACTUATOR_PORT:-8081}:8081
        depends_on:
            - mongodb

    mongodb:
        image: mongo:${MONGO_TAG:-4}
        restart: always
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb
        ports:
            - 27017:27017

volumes:
    mongo-data:
    mongo-config:
