version: '3'
services:
    backend:
        container_name: 'swosh'
        image: edholm/swosh:latest
        restart: always
        environment:
            - SWOSH_MONGODB_URI=mongodb://mongodb/swosh
        ports:
            - 8080:8080
            - 8081:8081
        depends_on:
            - mongodb

    mongodb:
        container_name: 'swosh-mongodb'
        image: mongo:4
        restart: always
        volumes:
            - mongo-data:/data/db
            - mongo-config:/data/configdb
        ports:
            - 27017:27017

volumes:
    mongo-data:
    mongo-config:
