server:
  port: ${SERVER_PORT:8080}
spring:
  data:
    mongodb:
      uri: ${SWOSH_MONGODB_URI:mongodb://localhost/swosh}
      repositories:
        enabled: true
  mustache:
    suffix: .html
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: [health, prometheus]
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}


# The interval between checking/deleting for old urls in milliseconds
swosh:
  hostname: ${SWOSH_HOSTNAME:swosh.me}
  scheme: ${SWOSH_SCHEME:https}
  expire:
    rate: ${SWOSH_EXPIRE_RATE:60000}
  users:
    - username: ${SWOSH_ADMIN_USERNAME:admin}
      password: ${SWOSH_ADMIN_PWD:admin}
  metrics:
    environment: ${SWOSH_ENVIRONMENT:local}
    server-hostname: ${SWOSH_SERVER_HOSTNAME:}
    app-name: ${SWOSH_APP_NAME:swosh}


logging:
  level:
    pub.edholm: ${LOG_LEVEL:TRACE}
