apiVersion: v1
kind: Namespace
metadata:
  name: swosh
  labels:
    name: swosh
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: swosh
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: swosh
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb
  namespace: swosh
subsets:
  - addresses:
      - ip: 192.168.1.5
    ports:
      - port: 27017
