name: Build, test, and deploy

on:
  push:
    branches:
      - master

jobs:
  build-gradle:
    name: Gradle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15

      - name: Cache Gradle cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlew-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload jar-file
        uses: actions/upload-artifact@v1
        with:
          name: libs
          path: build/libs/swosh.jar
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest
    needs: build-gradle
    env:
      REPO: edholm/swosh
    steps:
      - uses: actions/checkout@v1
      - name: Download jar-file
        uses: actions/download-artifact@v1
        with:
          name: libs
          path: build/libs/

        # This enables experimental features
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master

      - name: Login to Docker
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push arm64 container
        run: |
          VERSION=$(git describe HEAD)
          TAG="${REPO}:${VERSION}-arm64"
          echo Starting build of "$TAG"
          docker build --pull=true --platform arm64 --squash --tag="${TAG}" -f Dockerfile build/libs
          docker push "${TAG}"
        shell: bash

      - name: Build and push amd64 container
        run: |
          VERSION=$(git describe HEAD)
          TAG="${REPO}:${VERSION}-amd64"
          echo Starting build of "$TAG"
          docker build --pull=true --platform amd64 --squash --tag="${TAG}" -f Dockerfile build/libs
          docker push "${TAG}"
        shell: bash

      - name: Create manifest
        run: |
          VERSION=$(git describe HEAD)
          TAG="${REPO}:${VERSION}"
          LATEST="${REPO}:latest"
          docker manifest create --amend "${TAG}" "${TAG}-arm64" "${TAG}-amd64"
          docker manifest create --amend "${LATEST}" "${TAG}-arm64" "${TAG}-amd64"

          docker manifest push "${TAG}"
          docker manifest push "${LATEST}"
        shell: bash
  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: build-docker
    environment: Staging
    steps:
      - uses: actions/checkout@v1
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup docker context
        env:
          DOCKER_CONTEXT_HOST: ${{ secrets.DOCKER_CONTEXT_HOST }}
          DOCKER_CONTEXT_PORT: ${{ secrets.DOCKER_CONTEXT_PORT }}
          DOCKER_CONTEXT_SSH_USER: ${{ secrets.DOCKER_CONTEXT_SSH_USER }}
          DOCKER_CONTEXT_NAME: ${{ secrets.DOCKER_CONTEXT_NAME }}
        run: |
          ssh-keyscan -H -p ${DOCKER_CONTEXT_PORT} ${DOCKER_CONTEXT_HOST} >> ~/.ssh/known_hosts
          docker context create ${DOCKER_CONTEXT_NAME} --docker "host=ssh://${DOCKER_CONTEXT_SSH_USER}@${DOCKER_CONTEXT_HOST}:${DOCKER_CONTEXT_PORT}"
      - name: Deploy to staging
        run: |
          ./deploy.sh staging